/**
 * Widget Panel UI Component
 * 
 * Visual interface to browse, preview, and manage Phase 5 generated widgets
 * Implements G8 (efficient dismissal), G17 (user control), G18 (transparency)
 */

import { logger } from '../utils';
import type { StoredWidget, GeneratedWidget } from '../types';

export class WidgetPanel {
  private container: HTMLElement | null = null;
  private widgets: StoredWidget[] = [];
  private onInject: ((widgetId: string) => void) | null = null;
  private onPreview: ((widgetId: string) => void) | null = null;
  private onDelete: ((widgetId: string) => void) | null = null;
  private onRate: ((widgetId: string, rating: number) => void) | null = null;

  constructor() {
    this.createContainer();
  }

  /**
   * Create the widget panel container
   */
  private createContainer(): void {
    this.container = document.createElement('div');
    this.container.id = 'kairos-widget-panel';
    this.container.className = 'kairos-widget-panel';
    this.container.style.display = 'none';
  }

  /**
   * Show the widget panel
   */
  public show(
    widgets: StoredWidget[],
    callbacks: {
      onInject: (widgetId: string) => void;
      onPreview: (widgetId: string) => void;
      onDelete: (widgetId: string) => void;
      onRate: (widgetId: string, rating: number) => void;
      onDismiss: () => void;
    }
  ): void {
    logger.info('WidgetPanel', 'Showing widget panel', { count: widgets.length });

    this.widgets = widgets;
    this.onInject = callbacks.onInject;
    this.onPreview = callbacks.onPreview;
    this.onDelete = callbacks.onDelete;
    this.onRate = callbacks.onRate;

    // Ensure container is in DOM
    if (!document.body.contains(this.container!)) {
      document.body.appendChild(this.container!);
    }

    this.render(callbacks.onDismiss);
    this.container!.style.display = 'flex';
  }

  /**
   * Hide the widget panel
   */
  public hide(): void {
    if (this.container) {
      this.container.style.display = 'none';
    }
  }

  /**
   * Render the widget panel UI
   */
  private render(onDismiss: () => void): void {
    const html = `
      <div class="widget-panel-overlay"></div>
      <div class="widget-panel-content">
        <div class="widget-panel-header">
          <div class="widget-panel-title">
            <div class="widget-panel-icon">🛠️</div>
            <div>
              <div class="widget-panel-title-text">Generated Tools</div>
              <div class="widget-panel-subtitle">Proactively created based on your activity</div>
            </div>
          </div>
          <button class="widget-panel-close" id="widget-panel-close">×</button>
        </div>

        <div class="widget-panel-body">
          ${this.widgets.length === 0 ? this.renderEmptyState() : this.renderWidgetList()}
        </div>

        <div class="widget-panel-footer">
          <div class="widget-panel-help">
            These tools were generated by analyzing your browsing patterns with GUM
          </div>
        </div>
      </div>
    `;

    this.container!.innerHTML = html;

    // Attach event listeners
    document.getElementById('widget-panel-close')?.addEventListener('click', onDismiss);

    // Attach widget-specific listeners
    this.attachWidgetListeners();
  }

  /**
   * Render empty state when no widgets exist
   */
  private renderEmptyState(): string {
    return `
      <div class="widget-empty-state">
        <div class="widget-empty-icon">🤖</div>
        <div class="widget-empty-title">No tools generated yet</div>
        <div class="widget-empty-text">
          I'll analyze your activity and create helpful tools automatically.<br>
          Make sure "Proactive Tool Generation" is enabled in settings.
        </div>
      </div>
    `;
  }

  /**
   * Render list of widgets
   */
  private renderWidgetList(): string {
    return `
      <div class="widget-list">
        ${this.widgets.map(widget => this.renderWidgetCard(widget)).join('')}
      </div>
    `;
  }

  /**
   * Render a single widget card
   */
  private renderWidgetCard(storedWidget: StoredWidget): string {
    const { id, widget, createdAt, usageCount, userRating, isPinned } = storedWidget;
    const timeAgo = this.formatTimeAgo(Date.now() - createdAt);
    const toolType = widget.metadata.toolType || 'custom';
    const complexity = widget.metadata.complexity || 'moderate';

    return `
      <div class="widget-card ${isPinned ? 'pinned' : ''}" data-widget-id="${id}">
        <div class="widget-card-header">
          <div class="widget-card-type">
            ${this.getToolTypeIcon(toolType)} ${this.formatToolType(toolType)}
          </div>
          <div class="widget-card-badges">
            ${isPinned ? '<span class="widget-badge pinned">📌 Pinned</span>' : ''}
            <span class="widget-badge complexity complexity-${complexity}">${complexity}</span>
          </div>
        </div>

        <div class="widget-card-body">
          <div class="widget-card-objective">${widget.metadata.objective}</div>
          <div class="widget-card-meta">
            <span>Created ${timeAgo}</span>
            ${usageCount > 0 ? `<span>• Used ${usageCount}x</span>` : ''}
          </div>
        </div>

        <div class="widget-card-rating">
          ${this.renderStarRating(id, userRating)}
        </div>

        <div class="widget-card-actions">
          <button class="widget-action-btn preview-btn" data-widget-id="${id}" data-action="preview">
            <span class="btn-icon">👁️</span>
            <span class="btn-text">Preview</span>
          </button>
          <button class="widget-action-btn inject-btn primary" data-widget-id="${id}" data-action="inject">
            <span class="btn-icon">⚡</span>
            <span class="btn-text">Use Tool</span>
          </button>
          <button class="widget-action-btn delete-btn" data-widget-id="${id}" data-action="delete">
            <span class="btn-icon">🗑️</span>
          </button>
        </div>
      </div>
    `;
  }

  /**
   * Render star rating UI
   */
  private renderStarRating(widgetId: string, currentRating?: number): string {
    const stars = [1, 2, 3, 4, 5];
    return `
      <div class="star-rating" data-widget-id="${widgetId}">
        <span class="rating-label">Rate this tool:</span>
        ${stars.map(star => `
          <span class="star ${(currentRating && star <= currentRating) ? 'filled' : ''}" 
                data-widget-id="${widgetId}" 
                data-rating="${star}">★</span>
        `).join('')}
      </div>
    `;
  }

  /**
   * Get icon for tool type
   */
  private getToolTypeIcon(toolType: string): string {
    const icons: Record<string, string> = {
      calculator: '🧮',
      tracker: '📊',
      checker: '✅',
      analyzer: '🔍',
      formatter: '📝',
      monitor: '📈',
      custom: '🛠️',
    };
    return icons[toolType] || icons.custom;
  }

  /**
   * Format tool type for display
   */
  private formatToolType(toolType: string): string {
    return toolType.charAt(0).toUpperCase() + toolType.slice(1);
  }

  /**
   * Format time ago (e.g., "2h ago", "3d ago")
   */
  private formatTimeAgo(milliseconds: number): string {
    const seconds = Math.floor(milliseconds / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    const days = Math.floor(hours / 24);

    if (days > 0) return `${days}d ago`;
    if (hours > 0) return `${hours}h ago`;
    if (minutes > 0) return `${minutes}m ago`;
    return 'just now';
  }

  /**
   * Attach event listeners to widget cards
   */
  private attachWidgetListeners(): void {
    // Action buttons (preview, inject, delete)
    this.container!.querySelectorAll('.widget-action-btn').forEach(btn => {
      btn.addEventListener('click', (e) => {
        const target = e.currentTarget as HTMLElement;
        const widgetId = target.getAttribute('data-widget-id');
        const action = target.getAttribute('data-action');

        if (!widgetId) return;

        switch (action) {
          case 'preview':
            this.onPreview?.(widgetId);
            break;
          case 'inject':
            this.onInject?.(widgetId);
            break;
          case 'delete':
            if (confirm('Delete this tool? This action cannot be undone.')) {
              this.onDelete?.(widgetId);
              // Remove from UI
              const card = target.closest('.widget-card');
              card?.remove();
              
              // Update empty state if needed
              if (this.container!.querySelectorAll('.widget-card').length === 0) {
                const body = this.container!.querySelector('.widget-panel-body');
                if (body) {
                  body.innerHTML = this.renderEmptyState();
                }
              }
            }
            break;
        }
      });
    });

    // Star rating
    this.container!.querySelectorAll('.star').forEach(star => {
      star.addEventListener('click', (e) => {
        const target = e.currentTarget as HTMLElement;
        const widgetId = target.getAttribute('data-widget-id');
        const rating = parseInt(target.getAttribute('data-rating') || '0');

        if (!widgetId) return;

        // Update UI
        const ratingContainer = target.closest('.star-rating');
        ratingContainer?.querySelectorAll('.star').forEach((s, idx) => {
          if (idx < rating) {
            s.classList.add('filled');
          } else {
            s.classList.remove('filled');
          }
        });

        // Call callback
        this.onRate?.(widgetId, rating);
      });

      // Hover effect
      star.addEventListener('mouseenter', (e) => {
        const target = e.currentTarget as HTMLElement;
        const rating = parseInt(target.getAttribute('data-rating') || '0');
        const ratingContainer = target.closest('.star-rating');
        
        ratingContainer?.querySelectorAll('.star').forEach((s, idx) => {
          if (idx < rating) {
            s.classList.add('hover');
          } else {
            s.classList.remove('hover');
          }
        });
      });

      star.addEventListener('mouseleave', (e) => {
        const target = e.currentTarget as HTMLElement;
        const ratingContainer = target.closest('.star-rating');
        ratingContainer?.querySelectorAll('.star').forEach(s => {
          s.classList.remove('hover');
        });
      });
    });
  }
}

// Singleton instance
export const widgetPanel = new WidgetPanel();
